---
title: "Gov 50 Final Project"
author: "Isaac Tang"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Proposal

Does foreign support increase the likelihood of a coup d’etat being successful? In this study, I want to analyze the extent to which coup d'etats with a foreign backer result in a successful overthrow of an incumbent government. I hypothesize that coup attempts with foreign assistance are more likely to be able to seize power away from an incumbent government. Often, states that can lend support to coups in foreign countries are very powerful and have a lot of resources that they can utilize. This backing can come in the form of weapons supply, intelligence sharing, or even outright military or political support. Powerful countries that have backed coups in smaller states include the United States, United Kingdom, China, Russia/USSR, and France. These types of states all strive to maintain their national interests globally. Thus, not only can they provide the material support needed for a successful coup d’etat, they also have an incentive to ensure that any coup they support will end in success.My sample consists of 981 events that occurred between 1945 to the end of 2022. These events include 441 successful coups, 349 attempted coups and 191 coup conspiracies. Here, the explanatory variable of interest is whether or not the coup is characterized to have foreign backing (a foreign country provided support); this variable is labeled as “foreign”. The variable is coded as “= 1” for having foreign support, and “= 0” otherwise. The outcome variable of interest is the count of successful coup d’etats. In this dataset, it is characterized under “event_type”, and an event type of “coup” indicates that it is successful. Other event type outcomes include “attempted coup” (coup was initiated but defeated by the government) and “coup conspiracy” (coup was being planned but discovered before it could be initiated). This variable is measured from the Cline Center’s Coup d’État Project Dataset at the University of Illinois at Urbana-Champaign. If I observe that among coups with foreign backing have a higher success rate than coups without, then this would provide support for my hypothesis, However, if foreign backed coups have a lower success rate than coups without or if both types of coups have equal success rates, that would provide evidence against my hypothesis. 
